"""Add changes

Revision ID: 4eb1f82e9f16
Revises: 
Create Date: 2025-04-25 00:19:29.134775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb1f82e9f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popular_anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['mal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popular_anime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mal_id')

    # ### end Alembic commands ###
