"""Add synopsis to PopularAnime

Revision ID: 5b498238aa69
Revises: 56a2a35117fd
Create Date: 2025-04-09 16:59:13.444119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '5b498238aa69'
down_revision = '67c07610971d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = Inspector.from_engine(op.get_bind())
    if 'synopsis' not in [column['name'] for column in inspector.get_columns('popular_anime')]:
        op.add_column('popular_anime', sa.Column('synopsis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popular_anime', schema=None) as batch_op:
        batch_op.drop_column('synopsis')

    # ### end Alembic commands ###
